<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [['id'=>1,'description'=>'Central Region','name'=>'Buikwe'],
        ['id'=>2,'description'=>'Central Region','name'=>'Bukomansimbi'],
        ['id'=>3,'description'=>'Central Region','name'=>'Butambala'],
        ['id'=>4,'description'=>'Central Region','name'=>'Buvuma'],
        ['id'=>5,'description'=>'Central Region','name'=>'Gomba'],
        ['id'=>6,'description'=>'Central Region','name'=>'Kalangala'],
        ['id'=>7,'description'=>'Central Region','name'=>'Kalungu'],
        ['id'=>8,'description'=>'Central Region','name'=>'Kampala'],
        ['id'=>9,'description'=>'Central Region','name'=>'Kayunga'],
        ['id'=>10,'description'=>'Central Region','name'=>'Kiboga'],
        ['id'=>11,'description'=>'Central Region','name'=>'Kyankwanzi'],
        ['id'=>12,'description'=>'Central Region','name'=>'Luweero'],
        ['id'=>13,'description'=>'Central Region','name'=>'Lwengo'],
        ['id'=>14,'description'=>'Central Region','name'=>'Lyantonde'],
        ['id'=>15,'description'=>'Central Region','name'=>'Masaka'],
        ['id'=>17,'description'=>'Central Region','name'=>'Mityana'],
        ['id'=>18,'description'=>'Central Region','name'=>'Mpigi'],
        ['id'=>19,'description'=>'Central Region','name'=>'Mubende'],
        ['id'=>20,'description'=>'Central Region','name'=>'Mukono'],
        ['id'=>21,'description'=>'Central Region','name'=>'Nakaseke'],
        ['id'=>22,'description'=>'Central Region','name'=>'Nakasongola'],
        ['id'=>23,'description'=>'Central Region','name'=>'Rakai'],                     
        ['id'=>24,'description'=>'Central Region','name'=>'Wakiso'],
        ['id'=>115,'description'=>'Central Region','name'=>'Sembabule'],
        ['id'=>25, 'description'=>'Eastern Region', 'name'=>'Amuria'],
        ['id'=>26, 'description'=>'Eastern Region', 'name'=>'Budaka'],
        ['id'=>27, 'description'=>'Eastern Region', 'name'=>'Bududa'],
        ['id'=>28, 'description'=>'Eastern Region', 'name'=>'Bugiri'],
        ['id'=>29, 'description'=>'Eastern Region', 'name'=>'Bukedea'],
        ['id'=>30, 'description'=>'Eastern Region', 'name'=>'Bukwa'],
        ['id'=>31, 'description'=>'Eastern Region', 'name'=>'Bulambuli'],
        ['id'=>32, 'description'=>'Eastern Region', 'name'=>'Busia'],
        ['id'=>33, 'description'=>'Eastern Region', 'name'=>'Butaleja'],
        ['id'=>34, 'description'=>'Eastern Region', 'name'=>'Buyende'],
        ['id'=>35, 'description'=>'Eastern Region', 'name'=>'Iganga'],
        ['id'=>36, 'description'=>'Eastern Region', 'name'=>'Jinja'],
        ['id'=>37, 'description'=>'Eastern Region', 'name'=>'Kaberamaido'],
        ['id'=>38, 'description'=>'Eastern Region', 'name'=>'Kaliro'],
        ['id'=>39, 'description'=>'Eastern Region', 'name'=>'Kamuli'],
        ['id'=>40, 'description'=>'Eastern Region', 'name'=>'Kapchorwa'],
        ['id'=>41, 'description'=>'Eastern Region', 'name'=>'Katakwi'],
        ['id'=>42, 'description'=>'Eastern Region', 'name'=>'Kibuku'],
        ['id'=>43, 'description'=>'Eastern Region', 'name'=>'Kumi'],
        ['id'=>44, 'description'=>'Eastern Region', 'name'=>'Kween'],
        ['id'=>45, 'description'=>'Eastern Region', 'name'=>'Luuka'],
        ['id'=>46, 'description'=>'Eastern Region', 'name'=>'Manafwa'],
        ['id'=>47, 'description'=>'Eastern Region', 'name'=>'Mayuge'],
        ['id'=>48, 'description'=>'Eastern Region', 'name'=>'Mbale'],
        ['id'=>49, 'description'=>'Eastern Region', 'name'=>'Namayingo'],
        ['id'=>50, 'description'=>'Eastern Region', 'name'=>'Namutumba'],
        ['id'=>51, 'description'=>'Eastern Region', 'name'=>'Ngora'],
        ['id'=>52, 'description'=>'Eastern Region', 'name'=>'Pallisa'],
        ['id'=>53, 'description'=>'Eastern Region', 'name'=>'Serere'],
        ['id'=>54, 'description'=>'Eastern Region', 'name'=>'Sironko'],
        ['id'=>55, 'description'=>'Eastern Region', 'name'=>'Soroti'],
        ['id'=>56, 'description'=>'Eastern Region', 'name'=>'Tororo'],
        ['id'=>57, 'description'=>'Eastern Region', 'name'=>'Kapelebyong'],
        ['id'=>58, 'description'=>'Eastern Region', 'name'=>'Butebo'],
        ['id'=>59,'description'=>'Northern Region', 'name'=>'Abim'],
        ['id'=>60,'description'=>'Northern Region', 'name'=>'Adjumani'],
        ['id'=>61,'description'=>'Northern Region', 'name'=>'Agago'],
        ['id'=>62,'description'=>'Northern Region', 'name'=>'Alebtong'],
        ['id'=>63,'description'=>'Northern Region', 'name'=>'Amolatar'],
        ['id'=>64,'description'=>'Northern Region', 'name'=>'Amudat'],
        ['id'=>65,'description'=>'Northern Region', 'name'=>'Amuru'],
        ['id'=>66,'description'=>'Northern Region', 'name'=>'Apac'],
        ['id'=>67,'description'=>'Northern Region', 'name'=>'Arua'],
        ['id'=>68,'description'=>'Northern Region', 'name'=>'Dokolo'],
        ['id'=>69,'description'=>'Northern Region', 'name'=>'Gulu'],
        ['id'=>70,'description'=>'Northern Region', 'name'=>'Kaabong'],
        ['id'=>71,'description'=>'Northern Region', 'name'=>'Kitgum'],
        ['id'=>72,'description'=>'Northern Region', 'name'=>'Koboko'],
        ['id'=>73,'description'=>'Northern Region', 'name'=>'Kole'],
        ['id'=>74,'description'=>'Northern Region', 'name'=>'Kotido'],
        ['id'=>75,'description'=>'Northern Region', 'name'=>'Lamwo'],
        ['id'=>76,'description'=>'Northern Region', 'name'=>'Lira'],
        ['id'=>77,'description'=>'Northern Region', 'name'=>'Maracha'],
        ['id'=>78,'description'=>'Northern Region', 'name'=>'Moroto'],
        ['id'=>79,'description'=>'Northern Region', 'name'=>'Moyo'],
        ['id'=>80,'description'=>'Northern Region', 'name'=>'Nakapiripirit'],
        ['id'=>81,'description'=>'Northern Region', 'name'=>'Napak'],
        ['id'=>82,'description'=>'Northern Region', 'name'=>'Nebbi'],
        ['id'=>83,'description'=>'Northern Region', 'name'=>'Nwoya'],
        ['id'=>84,'description'=>'Northern Region', 'name'=>'Otuke'],
        ['id'=>85,'description'=>'Northern Region', 'name'=>'Oyam'],
        ['id'=>86,'description'=>'Northern Region', 'name'=>'Pader'],
        ['id'=>87,'description'=>'Northern Region', 'name'=>'Yumbe'],
        ['id'=>88,'description'=>'Northern Region', 'name'=>'Zombo'],
        ['id'=>89, 'description'=>'Western Region', 'name'=>'Buhweju'],
        ['id'=>90, 'description'=>'Western Region', 'name'=>'Buliisa'],
        ['id'=>91, 'description'=>'Western Region', 'name'=>'Bundibugyo'],
        ['id'=>92, 'description'=>'Western Region', 'name'=>'Bushenyi'],
        ['id'=>93, 'description'=>'Western Region', 'name'=>'Hoima'],
        ['id'=>94, 'description'=>'Western Region', 'name'=>'Ibanda'],
        ['id'=>95, 'description'=>'Western Region', 'name'=>'Isingiro'],
        ['id'=>96, 'description'=>'Western Region', 'name'=>'Kabale'],
        ['id'=>97, 'description'=>'Western Region', 'name'=>'Kabarole'],
        ['id'=>98, 'description'=>'Western Region', 'name'=>'Kamwenge'],
        ['id'=>99, 'description'=>'Western Region', 'name'=>'Kanungu'],
        ['id'=>100, 'description'=>'Western Region', 'name'=>'Kasese'],
        ['id'=>101, 'description'=>'Western Region', 'name'=>'Kibaale'],
        ['id'=>102, 'description'=>'Western Region', 'name'=>'Kiruhura'],
        ['id'=>103, 'description'=>'Western Region', 'name'=>'Kiryandongo'],
        ['id'=>104, 'description'=>'Western Region', 'name'=>'Kisoro'],
        ['id'=>105, 'description'=>'Western Region', 'name'=>'Kyegegwa'],
        ['id'=>106, 'description'=>'Western Region', 'name'=>'Kyenjojo'],
        ['id'=>107, 'description'=>'Western Region', 'name'=>'Masindi'],
        ['id'=>108, 'description'=>'Western Region', 'name'=>'Mbarara'],
        ['id'=>109, 'description'=>'Western Region', 'name'=>'Mitooma'],
        ['id'=>110, 'description'=>'Western Region', 'name'=>'Ntoroko'],
        ['id'=>111, 'description'=>'Western Region', 'name'=>'Ntungamo'],
        ['id'=>112, 'description'=>'Western Region', 'name'=>'Rubirizi'],
        ['id'=>113, 'description'=>'Western Region', 'name'=>'Rukungiri'],
        ['id'=>114, 'description'=>'Western Region', 'name'=>'Sheema']];
       
DB::table('districts')->insert($districts);
    }
}
