@extends('layouts.website')
@section('content')
    <div class="slider-area">
        <div class="slider-height2 slider-bg2 hero-overly d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 offset-sm-1">
                        <div class="hero__caption hero__caption2">
                            <h2>Privacy Policy</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="sample-text-area">
        <div class="container box_1170">
            <h3 class="text-heading">PRIVACY POLICY</h3>
            <p class="sample-text">
				In compliance with the African Union legislation, we inform you that our website will store some information about your preferences on your own computer inside a tiny file called a ‘cookie’. A cookie is a small piece of data that a website asks your browser to store on your computer or mobile device. The cookie allows the website to “remember” your actions or preferences over time. You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed. If you do this, however, you may have to manually adjust some preferences every time you visit a site and some services and functionalities may not work. Most browsers support cookies, but users can set their browsers to decline them and can delete them whenever they like.
 				A third-party website called aboutcookies.org has been set up to help you with instructions on how you can do that on various browsers.
            </p>
          <h3 class="text-heading">We use cookies to:</h3>
            <p class="sample-text">
              <ol>
                <li>Identify you as a returning user and to count your visits in our traffic statistics analysis;</li>
                <li>remember your custom display preferences;</li>
                <li>Suggest any recent searches you’ve made on our site</li>
                <li>Other usability features including tracking whether you’ve already given your consent to cookies</li>
              </ol>  
          		Enabling cookies from our website is not strictly necessary for the website to 
          		work but it will provide you with a better browsing experience. The cookie-related information is not used to identify you personally and 
          		the pattern data is fully under our control. These cookies are not used for any purpose other than those described here. 
          		There may also be other types of cookies created after you’ve visited our website. 
          		We use Google Analytics, a popular web analytics service provided by Google, Inc. 
          		Google Analytics uses cookies to help us to analyse how users use the site. 
          		The information generated by the cookie about your use of our website (including your IP address) will be transmitted to 
          		and stored by Google on servers in the United States. Google will use this information for the purpose of 
          		evaluating your use of our website, compiling reports on website activity and providing other services 
          		relating to website activity and internet usage. Google may also transfer this information to 
          		third parties where required to do so by law, or where such third parties process the information on Google’s behalf. 
          		Google undertakes not to associate your IP address with any other data held by Google.
            </p>
          <h3 class="text-heading">Third Party Advertising</h3>
            <p class="sample-text">
				We may have third-party advertising companies serving ads to you when you visit our website. 
                These companies may store information about your visits to our website and to other websites in order to provide you 
                with relevant advertisements about goods and services.</br>
				These companies may employ cookies and other identifiers to gather information which measures advertising effectiveness. 
				The information is generally not personally identifiable unless, for example, you provide personally identifiable information 
				to them through an ad or an e-mail message.
            </p>
          <h3 class="text-heading">Information Gathered by Third Party Advertisers</h3>
            <p class="sample-text">
				Cookies enable advertisers to learn about what ads you see, what ads you click, and other actions you take on our site and other sites. This allows advertisers to provide you with more useful and relevant ads. For example, if they know what ads you are shown while visiting our site, they can be careful not to show you the same ones repeatedly. They do not associate your interaction with unaffiliated sites with your identity in providing you with interest-based ads.
                We do not provide any personal information to advertisers or to third party sites. Advertisers and other third-parties (including the ad networks, ad-serving companies, and other service providers they may use) may assume that users who interact with or click on a personalized ad or content are part of the group that the ad or content is directed towards (for example, readers in the Pacific Northwest who read certain types of articles). Also, some third-party cookies may provide them with information about you (such as the sites where you have been shown ads or demographic information) from offline and online sources that they may use to provide you more relevant and useful advertising.
                If you would like to learn more about what options you have about limiting the gathering of information by third-party ad networks, you can consult the website of the Network Advertising Initiative.
                You can opt out of participating in interest-based advertising networks but opting out does not mean you will no longer receive online advertising. It does mean that the companies from which you opted out will no longer customize ads based on your interests and web usage patterns using cookie-based technology.

            </p>
			<h3 class="text-heading">Type and Purpose of Collection.</h3>
            <p class="sample-text">
				We collect information at various points in the Website to facilitate its use by our customers.
				Non-Personal Information: Upon accessing the Website, certain non-personal information will be automatically collected without your 
              	knowledge or consent, such as your IP address, location data (which is anonymous) and the referring website 
              	(“Non-Personal Information”). We use Non-Personal Information to examine our traffic and to view how our customers use the Website. 
              	This type of information will not allow you to be personally identified. For example, we use “cookies”, 
              	which contains only certain statistical information. You can instruct your computer to inform you whenever a cookie is being sent, 
              	or you can disallow cookies through your web browser. If you do choose to disallow cookies, your experience on the Website may be diminished, 
              	or your ability to choose some of the options on the Website may be limited.
            </p>
			<h3 class="text-heading">Sharing Information</h3>
            <p class="sample-text">
				We will not sell, rent or disclose to outside parties the information we collect, save and except that we may share the collected information with other parties as follows:
                </br></br>(a) Affiliated Service Providers:
                We have agreements with various affiliated service providers to facilitate the functioning of the Website, with whom we may share the information we have collected. For example, we may share your credit card information with the credit card service provider to process your purchase. All administrative service providers that we use are required to have the same level of privacy protection as we have, and therefore we expect that your information will be handled with the same level of care that we employ. Additionally, for example, we may use analytic or marketing services such as Google Analytics, Google Adsense, Taboola, or RevContent, to which collection you hereby unconditionally consent.

                </br></br>(b) Where required by law:
                We may share the collected information where required by law, specifically in response to a demand from government authorities where such demand meets the legal requirements.

                </br></br>(c) Statistical Analysis:
                We may share Non-Personal Information and aggregated information with third parties, including but not limited to for advertising or marketing purposes. 

                No Personal Information will be shared in this manner.

                </br></br>(d) Transactions:
                In connection with, or during negotiations of, any merger, sale of company assets, financing or acquisition, or in any other situation where Personal Information may be disclosed or transferred as one of our business assets.

            </p>
			<h3 class="text-heading">Choices and How To Opt Out Of Interest-Based Advertising</h3>
            <p class="sample-text">
				(a) Opting Out of Interest-Based 
					</br></br>
                Advertising Services: This website is a member of the Network Advertising Initiative (NAI) and adheres to the NAI Codes of Conduct as described on the NAI website. This website also adheres to the Digital Advertising Alliance (DAA) Self-Regulatory Principles. For a description of the DAA Program, please visit the DAA website. As described above, this website may use or transfer Device Data that it directly collects or that it receives from this website’s Customers, who may use cookies or non-cookie technologies, to enable advertising that is more tailored to Consumers’ inferred interests, preferences, and locations.
                This practice is known as interest-based advertising.
					</br></br>
                (b) Opting Out of Interest-Based Advertising by Third Parties.
				</br></br>
                This website may permit third parties to collect information on its Site and combine that information with other information collected on non-affiliated websites or applications over time. These third parties may use technologies, including cookies and web beacons, to collect information about Consumers’ or Customers’ use of the Site in order to analyze, report on, or customize content or advertising on this website or on other sites, or to help us operate and improve the Site. To find out more about interest-based advertising in the web environment, and how to opt-out of information collection for this purpose by companies that participate in the Network Advertising Initiative or the Digital Advertising Alliance, visit NAI’s opt-out page or DAA’s Consumer Choice Page.

				</br></br>
                <strong>Contact Us</strong>
                If you have any questions about this Privacy Policy, please email us at:
                <a href="mailto:info@appnomu.com" style="color:green;">info@appnomu.com</a>

				</br></br>
                <strong>Disclaimer:</strong> "This is a property of Bahati Media Group.  Content is protected under creative common license and is therefore protected from being reproduced in any manner for commercial purposes without any prior written permission from owners. For more information, Email us at <a href="mailto:info@appnomu.com" style="color:green;">info@appnomu.com</a>.
            </p>			
        </div>
    </section>
@endsection